from pydantic import BaseModel, Field
from typing import List

class ArchitecturePlan(BaseModel):
    """
    A structured plan generated by the LLM to satisfy a user requirement.
    """
    steps: List[str] = Field(
        description="A list of sequential steps required to fulfill the user's request. "
                    "Each step should be a clear, actionable instruction."
    )
    thought_process: str = Field(
        description="A brief explanation of why these steps were chosen to solve the requirement."
    )